// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/numoo-redesign-bento/Splash.tsx": () => import("../components/mockups/numoo-redesign-bento/Splash.tsx"),
  "./components/mockups/numoo-redesign-calm/Splash.tsx": () => import("../components/mockups/numoo-redesign-calm/Splash.tsx"),
  "./components/mockups/numoo-redesign-categories/Splash.tsx": () => import("../components/mockups/numoo-redesign-categories/Splash.tsx"),
  "./components/mockups/numoo-redesign-clinical/Splash.tsx": () => import("../components/mockups/numoo-redesign-clinical/Splash.tsx"),
  "./components/mockups/numoo-redesign-embrace/Splash.tsx": () => import("../components/mockups/numoo-redesign-embrace/Splash.tsx"),
  "./components/mockups/numoo-redesign-home/Splash.tsx": () => import("../components/mockups/numoo-redesign-home/Splash.tsx"),
  "./components/mockups/numoo-redesign-hospitality/Splash.tsx": () => import("../components/mockups/numoo-redesign-hospitality/Splash.tsx"),
  "./components/mockups/numoo-redesign-hybrid/Splash.tsx": () => import("../components/mockups/numoo-redesign-hybrid/Splash.tsx"),
  "./components/mockups/numoo-redesign-hybrid-nav/Splash.tsx": () => import("../components/mockups/numoo-redesign-hybrid-nav/Splash.tsx")
};
